module HusyHox.Utils (utilHarnesses, utils) where

import Prelude hiding (head, id, seq, sum, tail, truncate)

import Data.Map (Map)
import qualified Data.Map as M (fromList, map)

import HusyHox.Common.Utility
    (UtilityHarness, runUtility, GeneralUtility(..))

import HusyHox.File.Chcon     (chcon    )
import HusyHox.File.Chgrp     (chgrp    )
import HusyHox.File.Chmod     (chmod    )
import HusyHox.File.Chown     (chown    )
import HusyHox.File.CP        (cp       )
import HusyHox.File.Dircolors (dircolors)
import HusyHox.File.DD        (dd       )
import HusyHox.File.DF        (df       )
import HusyHox.File.Dir       (dir      )
import HusyHox.File.Install   (install  )
import HusyHox.File.LN        (ln       )
import HusyHox.File.LS        (ls       )
import HusyHox.File.Mkdir     (mkdir    )
import HusyHox.File.Mkfifo    (mkfifo   )
import HusyHox.File.Mknod     (mknod    )
import HusyHox.File.Mktemp    (mktemp   )
import HusyHox.File.MV        (mv       )
import HusyHox.File.RM        (rm       )
import HusyHox.File.Rmdir     (rmdir    )
import HusyHox.File.Shred     (shred    )
import HusyHox.File.Sync      (sync     )
import HusyHox.File.Touch     (touch    )
import HusyHox.File.Truncate  (truncate )
import HusyHox.File.Vdir      (vdir     )

import HusyHox.Shell.Arch     (arch     )
import HusyHox.Shell.Basename (basename )
import HusyHox.Shell.Chroot   (chroot   )
import HusyHox.Shell.Date     (date     )
import HusyHox.Shell.Dirname  (dirname  )
import HusyHox.Shell.DU       (du       )
import HusyHox.Shell.Echo     (echo     )
import HusyHox.Shell.Env      (env      )
import HusyHox.Shell.Expr     (expr     )
import HusyHox.Shell.Factor   (factor   )
import HusyHox.Shell.False    (false    )
import HusyHox.Shell.Groups   (groups   )
import HusyHox.Shell.Hostid   (hostid   )
import HusyHox.Shell.ID       (id       )
import HusyHox.Shell.Link     (link     )
import HusyHox.Shell.Logname  (logname  )
import HusyHox.Shell.Nice     (nice     )
import HusyHox.Shell.Nohup    (nohup    )
import HusyHox.Shell.Pathchk  (pathchk  )
import HusyHox.Shell.Pinky    (pinky    )
import HusyHox.Shell.Printenv (printenv )
import HusyHox.Shell.Printf   (printf   )
import HusyHox.Shell.Pwd      (pwd      )
import HusyHox.Shell.Readlink (readlink )
import HusyHox.Shell.Runcon   (runcon   )
import HusyHox.Shell.Seq      (seq      )
import HusyHox.Shell.Sleep    (sleep    )
import HusyHox.Shell.Stat     (stat     )
import HusyHox.Shell.Stty     (stty     )
import HusyHox.Shell.SU       (su       )
import HusyHox.Shell.Tee      (tee      )
import HusyHox.Shell.Test     (test     )
import HusyHox.Shell.Timeout  (timeout  )
import HusyHox.Shell.True     (true     )
import HusyHox.Shell.Tty      (tty      )
import HusyHox.Shell.Uname    (uname    )
import HusyHox.Shell.Unlink   (unlink   )
import HusyHox.Shell.Uptime   (uptime   )
import HusyHox.Shell.Users    (users    )
import HusyHox.Shell.Who      (who      )
import HusyHox.Shell.Whoami   (whoami   )
import HusyHox.Shell.Yes      (yes      )

import HusyHox.Text.Base64    (base64   )
import HusyHox.Text.Cat       (cat      )
import HusyHox.Text.Cksum     (cksum    )
import HusyHox.Text.Comm      (comm     )
import HusyHox.Text.Csplit    (csplit   )
import HusyHox.Text.Cut       (cut      )
import HusyHox.Text.Expand    (expand   )
import HusyHox.Text.Fmt       (fmt      )
import HusyHox.Text.Fold      (fold     )
import HusyHox.Text.Head      (head     )
import HusyHox.Text.Join      (join     )
import HusyHox.Text.MD5sum    (md5sum   )
import HusyHox.Text.NL        (nl       )
import HusyHox.Text.OD        (od       )
import HusyHox.Text.Paste     (paste    )
import HusyHox.Text.Ptx       (ptx      )
import HusyHox.Text.PR        (pr       )
import HusyHox.Text.Sha1sum   (sha1sum  )
import HusyHox.Text.Sha224sum (sha224sum)
import HusyHox.Text.Sha256sum (sha256sum)
import HusyHox.Text.Sha384sum (sha384sum)
import HusyHox.Text.Sha512sum (sha512sum)
import HusyHox.Text.Shasum    (shasum   )
import HusyHox.Text.Shuf      (shuf     )
import HusyHox.Text.Sort      (sort     )
import HusyHox.Text.Split     (split    )
import HusyHox.Text.Sum       (sum      )
import HusyHox.Text.Tac       (tac      )
import HusyHox.Text.Tail      (tail     )
import HusyHox.Text.TR        (tr       )
import HusyHox.Text.Tsort     (tsort    )
import HusyHox.Text.Unexpand  (unexpand )
import HusyHox.Text.Uniq      (uniq     )
import HusyHox.Text.WC        (wc       )

utilHarnesses :: Map String UtilityHarness
utilHarnesses = M.map runUtility utils

utils :: Map String GeneralUtility
utils = M.fromList
    -- file utils
    [ ("chcon"    , GU chcon    )
    , ("chgrp"    , GU chgrp    )
    , ("chmod"    , GU chmod    )
    , ("chown"    , GU chown    )
    , ("cp"       , GU cp       )
    , ("dd"       , GU dd       )
    , ("df"       , GU df       )
    , ("dir"      , GU dir      )
    , ("dircolors", GU dircolors)
    , ("install"  , GU install  )
    , ("ln"       , GU ln       )
    , ("ls"       , GU ls       )
    , ("mkfifo"   , GU mkfifo   )
    , ("mknod"    , GU mknod    )
    , ("mktemp"   , GU mktemp   )
    , ("mv"       , GU mv       )
    , ("mkdir"    , GU mkdir    )
    , ("rm"       , GU rm       )
    , ("rmdir"    , GU rmdir    )
    , ("shred"    , GU shred    )
    , ("sync"     , GU sync     )
    , ("touch"    , GU touch    )
    , ("truncate" , GU truncate )
    , ("vdir"     , GU vdir     )

    -- shell utils
    , ("["        , GU test     )
    , ("arch"     , GU arch     )
    , ("basename" , GU basename )
    , ("chroot"   , GU chroot   )
    , ("date"     , GU date     )
    , ("dirname"  , GU dirname  )
    , ("du"       , GU du       )
    , ("echo"     , GU echo     )
    , ("env"      , GU env      )
    , ("expr"     , GU expr     )
    , ("false"    , GU false    )
    , ("groups"   , GU groups   )
    , ("hostid"   , GU hostid   )
    , ("id"       , GU id       )
    , ("link"     , GU link     )
    , ("logname"  , GU logname  )
    , ("nice"     , GU nice     )
    , ("nohup"    , GU nohup    )
    , ("pathchk"  , GU pathchk  )
    , ("pinky"    , GU pinky    )
    , ("printenv" , GU printenv )
    , ("printf"   , GU printf   )
    , ("pwd"      , GU pwd      )
    , ("readlink" , GU readlink )
    , ("runcon"   , GU runcon   )
    , ("seq"      , GU seq      )
    , ("sleep"    , GU sleep    )
    , ("stat"     , GU stat     )
    , ("stty"     , GU stty     )
    , ("su"       , GU su       )
    , ("tee"      , GU tee      )
    , ("test"     , GU test     )
    , ("timeout"  , GU timeout  )
    , ("true"     , GU true     )
    , ("tty"      , GU tty      )
    , ("uname"    , GU uname    )
    , ("unlink"   , GU unlink   )
    , ("uptime"   , GU uptime   )
    , ("users"    , GU users    )
    , ("who"      , GU who      )
    , ("whoami"   , GU whoami   )
    , ("yes"      , GU yes      )

    -- text utils
    , ("base64"   , GU base64   )
    , ("cat"      , GU cat      )
    , ("cksum"    , GU cksum    )
    , ("comm"     , GU comm     )
    , ("csplit"   , GU csplit   )
    , ("cut"      , GU cut      )
    , ("expand"   , GU expand   )
    , ("factor"   , GU factor   )
    , ("fmt"      , GU fmt      )
    , ("fold"     , GU fold     )
    , ("head"     , GU head     )
    , ("join"     , GU join     )
    , ("md5sum"   , GU md5sum   )
    , ("nl"       , GU nl       )
    , ("od"       , GU od       )
    , ("paste"    , GU paste    )
    , ("pr"       , GU pr       )
    , ("ptx"      , GU ptx      )
    , ("sha1sum"  , GU sha1sum  )
    , ("sha224sum", GU sha224sum)
    , ("sha256sum", GU sha256sum)
    , ("sha384sum", GU sha384sum)
    , ("sha512sum", GU sha512sum)
    , ("shasum"   , GU shasum   )
    , ("shuf"     , GU shuf     )
    , ("sort"     , GU sort     )
    , ("split"    , GU split    )
    , ("sum"      , GU sum      )
    , ("tac"      , GU tac      )
    , ("tail"     , GU tail     )
    , ("tr"       , GU tr       )
    , ("tsort"    , GU tsort    )
    , ("unexpand" , GU unexpand )
    , ("uniq"     , GU uniq     )
    , ("wc"       , GU wc       )
    ]
